apiVersion: apps/v1
kind: Deployment
metadata:
  name: interpolator-host
  namespace: interpolator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interpolator-host
  template:
    metadata:
      labels:
        app: interpolator-host
    spec:
      containers:
        - name: interpolator-host
          image: hanneszbinden/baechlisbrunneschreck-interpolator:0.0.1
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              value: "User ID=postgres;Password=153c-34fc-4b65-845;Host=interpolator-db.interpolator.svc.cluster.local;Port=5432;Database=postgres;"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: interpolator-host
  namespace: interpolator
spec:
  selector:
    app: interpolator-host
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
